# Assume Python 3.9.
target-version = "py39"

# Assume several lldb and xnu-specific globals are built-in.
builtins = ["lldb", "kern", "cast", "addressof"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".eggs",
    ".egg-info",
    ".ruff_cache",
    "__pycache__",
    "dist",
]

[lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
# Disable ambiguous variable names and line lengths.
ignore = ["E741", "E501"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Unlike Flake8, default to a complexity level of 10.
mccabe.max-complexity = 10
